### ISSUE TITLE
Explore Different Parsing

### ISSUE THREAD

**Issue by arb** [stardog-union/stardog.js#108]
This thing could get crushed trying to do `JSON.parse` on a million rows.

Look into https://github.com/vigour-io/parse-large-json/blob/master/index.js as a possible solution.

**Comment by jmrog** [comment]
Another possibility: https://github.com/dominictarr/JSONStream (haven't looked into it much, though).

**Comment by sfkrauss** [comment]
Close / wouldn't do because of this ticket.
