### ISSUE TITLE
Windows: fetch always returning HPE_UNEXPECTED_CONTENT_LENGTH

### ISSUE THREAD

**Issue by sofayam** [stardog-union/stardog.js#114]
Any attempt at communication (including the simple example from your readme) will fail on windows (latest LTS v 6.11.2) with the following message

```Exception has occurred: Object
Promise Rejection (#<FetchError>)
FetchError: request to http://localhost:5820/Reminder/query failed, reason: Parse Error
    at ClientRequest.<anonymous> (c:\work\repos\stardogtest\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnData (_http_client.js:368:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) 


the values for err shown in the debugger are:


Error: Parse Error
bytesParsed:198
code:"HPE_UNEXPECTED_CONTENT_LENGTH"
message:"Parse Error"
stack:"Error: Parse Error\n    at Error (native)\n    at Socket.socketOnData (_http_client.js:363:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:547:20)"
__proto__:Error {name: "Error", message: "", constructor: function Error() { [native code] } …}

**Comment by snowell** [comment]
Hi, what version of Stardog are you using, and in which browser/version are you running the JS?

**Comment by sofayam** [comment]
Thanks for getting back on this.

I am using Stardog 5.02, node 6.11.2  and 1.0.0-rc2 of the stardog.js library (the one I get when I do an npm install stardog.js)

**Comment by arb** [comment]
Please post your code as well. It would help to see what you are doing.

**Comment by snowell** [comment]
I was able to pin down the issue. It is most directly caused by a known issue in Stardog 5.0.2 that is fixed for 5.0.3, which is to be released today. The HPE_UNEXPECTED_CONTENT_LENGTH error could still potentially happen on _other_ errors, which is a server issue that will be looked into. Thanks for reporting!

**Comment by sofayam** [comment]
@arb it's just the simple example from your readme.

**Comment by snowell** [comment]
@sofayam With the release of Stardog 5.0.3, you should no longer be experiencing this issue.
