### ISSUE TITLE
ReadMe out of sync with npm repository

### ISSUE THREAD

**Issue by sofayam** [stardog-union/stardog.js#115]
The "Quick Example" at https://www.npmjs.com/package/stardog, and also in the README.md which you get in your node_modules copy, has a couple of bugs which are not present in the github version of the readme.

Nothing drastic but it stops you in your tracks if you are a newb just trying to get something to work.

**Comment by snowell** [comment]
Hi,

What are some examples of these bugs? In testing #114 I was copy/pasting from the "quick example" and it was working fine.

**Comment by sofayam** [comment]
Here is the example from my node_modules

## Quick Example
```js
const { Connection, query } = require('stardog');

const conn = new Connection({
  username: 'admin',
  password: 'admin',
  endpoint: 'http://localhost:5820',
});

query.execute(conn, 'select distinct ?s where { ?s ?p ?o }', {
  limit: 10,
  offset: 0
}).then(({ result }) => {
  console.log(result.results.bindings);
});
```
The database is missing in the call to execute and the parameter coming back from the "then" should be "body" -- all fixed in your current github readme.

**Comment by snowell** [comment]
Ah, nice catch! It looks like NPM doesn't allow README changes without a version number change, so we'll just need to figure out what we want to do there
