### ISSUE TITLE
Add support for 'list' endpoint for virtual graphs

### ISSUE THREAD

**Issue by jmrog** [stardog-union/stardog.js#195]
Currently, stardog.js has a `list` method for virtual graphs that does not actually hit the virtual graphs "list" endpoint (instead, it just hits `admin/virtual_graphs`, which returns only the names of all VGs rather than all of their info objects). We should support hitting `admin/virtual_graphs/list` as well. We could either add a new method for this, or just change the endpoint hit by the existing `list` method. If we do the latter, it'll be a breaking API change, so we should include it only in stardog.js 2.0+.

**Comment by brianru** [comment]
TODO in #194  ?
