### ISSUE TITLE
How do you control reasoning on/off for a queryexecute?

### ISSUE THREAD

**Issue by CoryCasanave** [stardog-union/stardog.js#216]
Could not find in documentation, probably in same place as "limit", but that is also not documented here.
Also, do the pragmas work either way?

**Comment by jmrog** [comment]
> Could not find in documentation, probably in same place as "limit", but that is also not documented here.

Yes, it's in the same place as "limit" (just using "reasoning" as the property name). We'll try to update the docs to indicate this.

> Also, do the pragmas work either way?

Do you mean the reasoning pragmas? They work in the same way as described here (they must appear in the body of the query): https://www.stardog.com/docs/#_query_answering

**Comment by CoryCasanave** [comment]
Thanks
