### ISSUE TITLE
Clarify the db.create signature

### ISSUE THREAD

**Issue by maka-io** [stardog-union/stardog.js#222]
The documentation says:
options ({ files: { filename: string}[] })

That isn't real json / javascript.  Could you clarify?

**Comment by jmrog** [comment]
> The documentation says:
> options ({ files: { filename: string}[] })
> 
> That isn't real json / javascript. Could you clarify?

Sorry for the confusion. This is a _type_ annotation, so while it isn't "real json/javascript," it is real TypeScript (and is also similar in style to JSDoc type annotations). What it means is that the `options` parameter should be an object with a `files` property, where the value of the `files` property should be an array of objects each of which has a string `filename` property. In other words, the `options` parameter should look like this:

```
{
  files: [
    {
      filename: 'myFile1.txt',
    },
    {
      filename: 'myFile2.txt',
    }
  ],
}
```
