### ISSUE TITLE
Can't seem to make a variable that includes bindings from an OPTIONAL clase

### ISSUE THREAD

**Issue by arbazhamayun** [stardog-union/stardog.js#46]
conn.query({
          database: proj,
          query:`select ?uri ?ID ?typeID ?topNode ?multiID \
                 where { \
                 ?uri a ?type.  \
                 ?uri ccs:singleLevelID ?ID .  \
                 OPTIONAL {?uri ifcowl:objectType_IfcObject/express:hasString ?type2 .} \
                 OPTIONAL {?uri ccs:typeID ?typeID .} \
                 OPTIONAL {?uri ccs:topNode ?topNode .} \
                 OPTIONAL {?uri ccs:multiLevelID ?multiID .} \
                 }`
        }, function (data) {
        console.log(data.results.bindings);

for (var i in data.results.bindings) {
                var uriV = data.results.bindings[i].uri.value;
                var topnode = data.results.bindings[i].topNode.value;
                var singleID = data.results.bindings[i].ID.value;
                var TypeID = data.results.bindings[i].typeID.value;
}

Error I get :

/home/ubuntu/workspace/server/mhra.js:123
                var TypeID = data.results.bindings[i].typeID.value;
                                                            ^

TypeError: Cannot read property 'value' of undefined
    at /home/ubuntu/workspace/server/mhra.js:123:61
    at Request.fnResponseHandler (/home/ubuntu/workspace/server/node_modules/stardog/js/stardog.js:186:21)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request._fireSuccess (/home/ubuntu/workspace/server/node_modules/restler/lib/restler.js:226:10)
    at /home/ubuntu/workspace/server/node_modules/restler/lib/restler.js:158:20
    at Request._encode (/home/ubuntu/workspace/server/node_modules/restler/lib/restler.js:197:9)
    at /home/ubuntu/workspace/server/node_modules/restler/lib/restler.js:154:16
    at Gunzip.onEnd (zlib.js:213:5)
    at emitNone (events.js:91:20)

**Comment by jmrog** [comment]
The `OPTIONAL` keyword is useful for graph patterns that define/add bindings to solutions only when the pattern matches; when the pattern _doesn't_ match, the solution is left unchanged. In the case where you received the error you described, the pattern did not match, and so a binding for `typeID` was not defined. If you want to prevent the error, then (since the binding is optional) you can simply check whether the binding has been defined first, as in:

```
var typeID;
if (data.results.bindings[i].typeID) {
  typeID = data.results.bindings[i].typeID.value;
}
```
