### ISSUE TITLE
No support for update queries

### ISSUE THREAD

**Issue by rivettp** [stardog-union/stardog.js#73]
As far as I can see there is no support for these verbs i.e. insert (data) and delete (data), which require /update instead of /query in the URL.

**Comment by arb** [comment]
Are you looking for addInTransaction and deleteInTransaction?

https://github.com/stardog-union/stardog.js/blob/master/js/stardog.js#L658

**Comment by rivettp** [comment]
I don't think so, but am new to Stardog so happy to be convinced. I'm looking for an atomic (no explicit transaction) JS front end to the http mechanism to insert or delete triples using INSERT, INSERT DATA, DELETE or DELETE DATA  in SPARQL - which I believe requires use of "/update"  in the URL as per https://www.stardog.com/docs/#_sparql_update_2  (I've tried those using /query and get an error).

**Comment by rivettp** [comment]
We did develop the bones of such a function in a fork of stardog.js (the file) and I was planning to do a PR once better fleshed out, but I see the structure has now completely changed and stardog.js is no more.

**Comment by snowell** [comment]
@rivettp You are welcome to create a PR against `master` or `tags/v0.3.1` that includes update functionality. As you've noticed, in `develop` there is a substantial rewrite going on, which we will make sure has the missing functionality when it's ready to be published.

**Comment by rivettp** [comment]
This is addressed by #88 which was in effect a duplicate issue, so closing this.
