### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by arb** [stardog-union/stardog.js#85]
## List of known missing endpoints

- [x] get list of stored procedures
- [x] remove specified set of ICV axioms
- [x] ICV isValid check
- [x] ICV get all ViolationBindings
- [x] ICV get specific ViolationBindings
- [x] ~~[SPARQL updates](https://www.stardog.com/docs/#_sparql_update_2)~~
- [ ] ~~List of stored procedures~~
- [x] reasoning explain
- [x] removeICV

**Comment by tysoeh** [comment]
[icv methods](https://github.com/stardog-union/stardog/blob/develop/icv/api/main/src/com/complexible/stardog/icv/ICValidator.java)

**Comment by rivettp** [comment]
SPARQL update queries (see #73)
